"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$all\
$username \
$character"""

palette = 'colors'

[palettes.colors]
primary = '{{colors.source_color.default.hex}}'

[aws]
symbol = "  "
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[[battery.display]]
threshold = 15

[buf]
symbol = " "

[bun]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[c]
symbol = " "
format = '\[[$symbol($version(-$name))]($style)\]'

[cpp]
symbol = " "
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'

[cobol]
format = '\[[$symbol($version)]($style)\]'

[conda]
symbol = " "
format = '\[[$symbol$environment]($style)\]'

[crystal]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[daml]
format = '\[[$symbol($version)]($style)\]'

[dart]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[deno]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[directory]
read_only = " 󰌾"
style = 'bold white'

[docker_context]
symbol = " "
format = '\[[$symbol$context]($style)\]'

[dotnet]
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'

[elixir]
symbol = " "
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[erlang]
format = '\[[$symbol($version)]($style)\]'

[fennel]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[fossil_branch]
symbol = " "
format = '\[[$symbol$branch]($style)\]'

[gcloud]
symbol = "  "
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
symbol = " "
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[gradle]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[guix_shell]
symbol = " "
format = '\[[$symbol]($style)\]'

[haskell]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[haxe]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[helm]
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
symbol = " "
format = '\[[$symbol$branch]($style)\]'

[java]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[julia]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[kotlin]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
symbol = "󰍛 "
format = '\[$symbol[$ram( | $swap)]($style)\]'

[meson]
symbol = "󰔷 "
format = '\[[$symbol$project]($style)\]'

[nim]
symbol = "󰆥 "
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
symbol = " "
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[ocaml]
symbol = " "
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[opa]
format = '\[[$symbol($version)]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[os]
format = '\[[$symbol]($style)\]'

[package]
symbol = "󰏗 "
format = '\[[$symbol$version]($style)\]'

[perl]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[php]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[pijul_channel]
symbol = " "
format = '\[[$symbol$channel]($style)\]'

[pixi]
symbol = "󰏗 "
format = '\[[$symbol$version( $environment)]($style)\]'

[pulumi]
format = '\[[$symbol$stack]($style)\]'

[purescript]
format = '\[[$symbol($version)]($style)\]'

[python]
symbol = " "
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[raku]
format = '\[[$symbol($version-$vm_version)]($style)\]'

[red]
format = '\[[$symbol($version)]($style)\]'

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[rust]
symbol = "󱘗 "
format = '\[[$symbol($version)]($style)\]'

[scala]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[spack]
format = '\[[$symbol$environment]($style)\]'

[sudo]
format = '\[[as $symbol]($style)\]'

[swift]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[time]
format = '\[[$time]($style)\]'

[username]
disabled = false
show_always = true
format = '[$user](bold primary)'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[solidity]
format = '\[[$symbol($version)]($style)\]'